name: 'Small Business default config'
type: module
description: 'Imports default config when a module is enabled'
package: Web services
core: 8.x
dependencies:
  - smallbusiness_default_content

# Information added by Drupal.org packaging script on 2021-05-28
version: '8.x-1.74'
project: 'druppio_small_business_distribution'
datestamp: 1622199056
